name: Update CBPAY Holders Data

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  actions: read

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Debug - Check files before script
      run: |
        echo "Files before running script:"
        ls -la *.json || echo "No JSON files found"
        echo "Current directory:"
        pwd
        echo "All files:"
        ls -la
    
    - name: Run data collection script
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        echo "Running data collection script..."
        python get_cbpay_enhanced_data.py
        echo "Script completed with exit code: $?"
    
    - name: Debug - Check files after script
      run: |
        echo "Files after running script:"
        ls -la *.json || echo "No JSON files found"
        echo "Git status:"
        git status
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Pull latest changes and commit updates
      run: |
        echo "Pulling latest changes..."
        git pull origin main --rebase || echo "Pull failed or no changes to pull"
        
        echo "Adding files to git..."
        git add cbpay_holders.json cbpay_market_data.json cbpay_large_transactions.json || echo "Some files may not exist"
        
        echo "Checking for changes..."
        if git diff --staged --quiet; then
          echo "No changes to commit - this is normal if APIs didn't return new data"
          exit 0
        else
          echo "Changes detected, committing..."
          git commit -m "Update CBPAY data - $(date)"
          echo "Pushing changes..."
          git push origin main
          echo "Push completed successfully"
        fi


